version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/news_board
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=news_board_db
      - POSTGRES_USER=news_board_db_user
      - POSTGRES_PASSWORD=1234

  redis:
    image: redis
    hostname: redis
    ports:
      - '6379:6379'

  celery:
    build: .
    command: celery -A news_board.celery worker --loglevel=INFO
    volumes:
      - ./news_board:/usr/src/app
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    command: celery -A news_board.celery beat --loglevel=INFO
    volumes:
      - ./news_board/:/usr/src/app/
